# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3e203036fef465ab871f8abc2f15127573aa93e5124bf1a20c7298523a9081b86858d25e862312077744dc71bb4ea44cb47f9db74fd2e76143c611250101b1

test:
  secret_key_base: bccfdf54f75893428ecff88b877d9c63ed97df39baf3180e3d28632f9d416ac0fad5f661bfccc55e425fa661fd5c464e8fff27f90c78913051a59e17bf056313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
